services:
    certbot:
        image: ENC[AES256_GCM,data:spbpKtCvwzk+OnWBPeSFPIvbjxUR8w==,iv:n5Iy8zZycjSDud7AnQKkUVCjbfZzO6s3JAnBaUOfvTQ=,tag:oLOD/qwR23CPaXjQBtIXXw==,type:str]
        volumes:
            - ENC[AES256_GCM,data:GowuDyLnn67gENPodAF76ey9LZn3JCzMHdWjZLrP,iv:lPFem7gA8zwWNYvH8ASPbJpnnSE8FzOcPji5l8Tv3KQ=,tag:ODK5vfJLFVYRdiW4lwJuYw==,type:str]
            - ENC[AES256_GCM,data:m6J/uV7BeTMquseglvxSz5oEwQoUpUjDRsGi8FlDEy6pTB9rcD8H2A==,iv:5RUYwUjnHaGmrjfyFQoz3zETA3kTaDtu0anI54og9e8=,tag:LO6b/t0+hVdRpaP/5nEfzw==,type:str]
        command: ENC[AES256_GCM,data:JMtrn12+T0Hc0Em5cmQJaBezCXj0d8s9DZJcOE/L9Z4ZH5jpMBvZGMUb5BC6ATJyMFyCh56V9V5VpHmyXZjkjpw7KfFFrfIvPo0rvD4VDtxkDYePL6CZxVbSol+Gs1dfyrLakcydnH8kWZklSm39mqE195tapCMgGwUo+XviE3O4BCziFUjCy5Jxf35tf4+T03yZoNt8tTEMAiCiOn8qUWM0+UvRdQQhrfHOOFID3eU98/33qorNCu2lh0PYJ8lqiN7ghX8XErPZt2ii6/cpAlegb+PjGCyBn3z+LKSmaKkEEUF4S7Gz,iv:v+P3Hj7TGPduWVsjuf+4QJcKSbjXlkZJ8Yk8nipKS0Q=,tag:AK3D2uwh0Om8XbNSRmXMxQ==,type:str]
        networks:
            - ENC[AES256_GCM,data:bjGlYA==,iv:4DsVQ1cTMSuV1dRqTyRysPQKptt/jYRwcKhnJQxA+dU=,tag:QAm6OR9s1+AiSGV9C6JEjQ==,type:str]
networks:
    cert:
        driver: ENC[AES256_GCM,data:KD7/lr/J,iv:ixJSYupHCIWNw2oOT+/g+jmoAJpHz4gKdzMwDy7Ejzc=,tag:mIE75NNCw5T+oxhNuPkg7g==,type:str]
sops:
    age:
        - recipient: age1873xyakw74p6jlcrausq0e9mmh5ch5en2l3nlg6a8d2qtxxmkqdqthddvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbkFUczU2UXpRWTMxSTRp
            Z1pZQUNTdGdBYTBkTWZ6MUNYOWlKVVNuSkdvCmw2bmlWVGp5a3BzZ05zNzdGWkxq
            T1FYeDNMcDZua2RxV2dzWE94ZDVrenMKLS0tIFlOeUR4NG1YMS9idFNYd3lJbldV
            S2pGVnRZWkVRL24wem9hanF2eURNMWsKXG7MjEoytPdMX+9SROc8ITSeq4Y1mnpH
            NJhvuwWRz78/MRXlXdt5pvwW+VlWHXGsJXPIsGkLwh54C9sxq7DRxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1helrvdx65wx4e7sauvut57nc288ycth5884mvxag2kmrguvgtfnqayy8uw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaG94bXNES200Q2JYTVQv
            VmxpdGpZazQzbVB1ZGlMaVViMElLYWxFblRJCnRTWFVBQXBSSEJSZ1pvM1NwWXFl
            ZDBYaC9wTHBCelNEelhOTksvdXdBbTQKLS0tIDNqaG1HRTExZDVySm1ZS3pJUjZ6
            M0hiL3FlaDdQZ090TFdUVHN1VmxydHMKMd+8vmN8+I0yDIFwWOzur8875hno4Nan
            d9DyNDzXazHwjVOp7yDEdUDN3c4zb86n0+31hjxkP+3shQqbxvZFBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T04:34:54Z"
    mac: ENC[AES256_GCM,data:emSXu89tgloo4KTkv8cGzdZXK2onEMGQ9yxUch/1zpWr9oX0sOplXNsKRfIP8IbKFuqCZWVfCs+jIQi/NTzlILUwZY4W6Vpn9TwQKMwifu6hyDEuZyglvxSRIi4LMRj2vMHvlywTcOKhOXAAw2q7Jfrw4kiWPQ5fwEIQAkSGy0o=,iv:Z/jcWviCTf/uuDVY1Lubg9Uue96uzSJpBhaBx0HGyT4=,tag:/cILMpahgzkJefSNtuTB9w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
