services:
    certbot:
        image: ENC[AES256_GCM,data:XcabK3XNqvJroc11CLIPkVqQlQQK/Q==,iv:D9Rn6cuyfbNJLX6zn8e84066Ps9l/a72KPF7aMkSuck=,tag:QPC8ih9EkUd/9hbipHt31g==,type:str]
        volumes:
            - ENC[AES256_GCM,data:27isOIp/WuGsALAWdI9NxMsk3deHR731klDkcGFQ,iv:jqdWZrLKWP6bh5Fx45zDvy+H6zdrY1yfnRfG8zJhzG8=,tag:cdlHuMbKrMp8ASyou8JMHQ==,type:str]
            - ENC[AES256_GCM,data:bU/Kh2Y82hifTzW2lwrDrY0mOIYEckX8FCTscqGBGs0rY6acivc2JA==,iv:ISJ1amzkBh4tFQ2eq0UD/JOXyzZDeJk5/o8NNiYMGns=,tag:QEnoZrt0cTmz+3jE6aNbFw==,type:str]
        command: ENC[AES256_GCM,data:1uHrRBg/OZRQUoJfjWD1onAHVrFJVVnvsvjniJ4hyieDO1rAScK2kFsOLbm47boOISWQcpGPbNJAbH9fOFQxt3GhRSMfEjW1NoLCO6QeTVeY9Ti6QkvsHwrfiL7T0kLGRTXVbjur26jkz/7dW0swmR42Z29ciJtF/Whq2lj/oAjJk2f2T+NMXdl9xkRcIN15iOahTrQ8GsBkLhT/HEyUms0AEyadLgC8PiFjZJ87j4dcgOIexljA9okJCPB5cRo0dwqqxIcALmfizoo37rl66vFeNwEtm/Sa7v8yPNXdPaizDYO5fT6H,iv:wr5eoO18nuIUEwQBgjKS37n0RFqPTQHaJmAzsgiphL0=,tag:mO5cgd2cb2Y23+EGlwvFxg==,type:str]
        networks:
            - ENC[AES256_GCM,data:jfX+XA==,iv:+WDL3kB7pfNzPw9Mj1RKgasK6Mwh0ZiSm8F+2v/KFyg=,tag:Bxgkl+YM/c1GM4F7lXPCBQ==,type:str]
networks:
    cert:
        driver: ENC[AES256_GCM,data:QmMCv72j,iv:Ki6IR9VOApmyqG7ITfphIgCPReNfOARj/PMScrx/gyk=,tag:9HojbWfSa1f9E0cdpE9H2g==,type:str]
sops:
    age:
        - recipient: age1873xyakw74p6jlcrausq0e9mmh5ch5en2l3nlg6a8d2qtxxmkqdqthddvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSHZ4SjdiQkpFNVhEZDh1
            ZVB4UDFtRUJTTDN1Yk4xaG4rY2ZJZ3dkR0J3CkJqdnVLdXJmWkRsOG5BSDk0c29j
            MWhJdE5hc3UvQmhCSDc0ZlE0L3lzajQKLS0tIDRUSkkwc0FrZll0dDBzQU9oWVU0
            V3B2cVM1VlBNeVB0Zk9pWmhFekxKR3cKHt5tFeHB5Iz54S0oDu7Zrjo4wKwYJJbL
            zXE1VcQV2PVvHPxjfzyW/FUwlkHqbxk8Iv7TkR7DgQlU9A2EYlZxMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1helrvdx65wx4e7sauvut57nc288ycth5884mvxag2kmrguvgtfnqayy8uw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRFJ4b2VqSnBvQ3FkVUgz
            UkhKV3M3TU4yUTROUUpLU0FXTkJWWmdkaVRZCjc5SzYvN2E1a0o1VlFDRkVzT2s2
            aFhKL3U4Nk1nM2JDb2hFeXZDNkh6VlEKLS0tIG9NUHU0RzNaUUpSdEpsNGZlaUFM
            aG8yVHlmWXVXS1NIWEhiU3N4dmhjdDgKTjzhLDaebVVEBPmVizBeDUCf2PwZZxnD
            5gjQAw3x52n9MlS00xeZr3JDGAqYGNgp8Tqmv3InnfffLY6n5fMvjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-18T12:33:58Z"
    mac: ENC[AES256_GCM,data:/pecfEdwKypCqP85WWfIEdVtCTevY568NRz+jUBV+Wojs4/oFRkB2GU2l4aybIAivZe2jxS/5rp18L7z5Q7LYHB93awWTyIvaEDb5y6xU86NJwjiEGtfySDisVYopbV7S73vR4Y3O1Q/MqBCaCj8k32O+z8J3eLucvEc1h+DCNw=,iv:C/H8FsSGiA50T9ZEf/HQesNaw7bJUwCtaOW4oGnU0NM=,tag:C9O2iIU0+1BWKoYQn/Uuww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
