services:
    certbot:
        image: ENC[AES256_GCM,data:nw4OR4SqYOkfP+OPbmdjjJ3K/LkPzw==,iv:yHX2lhwnpt48CHB3FKyPvUylyVrA9I35FzRg0d6cNh4=,tag:wGCSW9DB7+6njT+rYQ0DcQ==,type:str]
        volumes:
            - ENC[AES256_GCM,data:vVkHFF7PqCN1Pnz7QWoil+H/dGZJwBSo,iv:n1IbeXeA6rrN6sbPn98HixwfPlWD/VALIB/Cj8XLGoQ=,tag:34eORI18ygexieYdPy2R4Q==,type:str]
            - ENC[AES256_GCM,data:zpTjNU1PvC7vQ7YMDhSqfiO9oGnjdIFdttQnpMd9HPOaoOdlGYqaVQ==,iv:fvpKIoBMvhAFamyMZ1uvafmeFANBEwuU9BXiCLie3EA=,tag:M0hxOjHOWmnGrn/J94vgeg==,type:str]
        environment:
            EMAIL: ENC[AES256_GCM,data:3ECbLGfvL8hmXWQBlv4QFzcl4VCjunOzXUAJAk99ArWMbzw=,iv:K7isuZdlSd9WoS4jcnK+5+3rPq06qb2BX2SxPowv+IY=,tag:6HYGE79NQuyutTKPgVQSCg==,type:str]
            SERVER_NAME: ENC[AES256_GCM,data:71ivd2A/q+PlpcMQqaNjO55Z,iv:DJWOUY2ESiOOLSW40T6aCvNjWlEDUgOrjtlrIwARmU8=,tag:f5C38FiwbBL+Aqkpt6MW/Q==,type:str]
        command: ENC[AES256_GCM,data:8+XjnRY9I6ssHcIu5CGclUIgF9paoAbOK/n/I3gT60oDuwSi/fBWk6RMGE1FaUR6RY85ZGgMxWPsxpiJUl88/PjhZ6RY7Bnpr1JgOLDjGku8mGV8qqcxDIeHjZzNcM5o0Sh8Zu6LC8uDKIahn05Yp/J9fcgeGCkYtwuCh6GSOPHRqtRCfStjPvdWYl91yuBLxCNVqRRlE5dcK9QOA8MsYjmdgMYLgZu9OHzRLaethi5YfJfnp38jJEs+Hs2KWN+IHir+sZ5uFiE=,iv:3qiLJZ5sXHJ9eomKY9X5BzW+CcAeXLOpqnWE3XvID6o=,tag:qvpy1KxuuIK4tzstpizIUQ==,type:str]
        networks:
            - ENC[AES256_GCM,data:qKjPFg==,iv:bC+qo7vFNdIpY4bHF6aSr5jt1o+zY3zBW4WxECvYGQ0=,tag:H1roFV3IEWfV7xKJ3DQZMA==,type:str]
networks:
    cert:
        driver: ENC[AES256_GCM,data:1pH8kDuH,iv:KYi3l4hFyF8wGrvoNxugqsAb2dCR90pr8gfvH61PGrg=,tag:t0yRUQoeEiHA5v3F+22NDw==,type:str]
sops:
    age:
        - recipient: age1873xyakw74p6jlcrausq0e9mmh5ch5en2l3nlg6a8d2qtxxmkqdqthddvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1L3FIRWw4V2pvMjZGd2lh
            a08vL25qYkxUd3hHOVlWMlRNZWRnbjBySVdvCk1zT1NDRXI2N1VkNUhNVW9YdVhU
            ZnhVL0RUWEVmRkkvc0RpeHFyRW0vd1kKLS0tIHJBVFkvOUhjVEZYTVY4a0xFL1I0
            djBlNUNOdmRsN01weEpXSkFCTVdRVWMK9HbHBryzx7m2d88+NLGogrHCPMPOmKcG
            eBLZdZ+TKtfF2bHZe79LGeu4erBgzMbta3rRld5Iu+6ii4K9zJuoYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T12:29:08Z"
    mac: ENC[AES256_GCM,data:4HSCyP5OqWwGpn8Tqn1oVjTYUPGVW7pOE27Xt7MOjW58Wcg1ZtrhTQopuCeMlf4Qt4rk+4edmgafIBfpDfemH/WJ74sf31O18RuLn4Neurb6Jx9PU6ofX1/m6b7cbpV5KoQPxPxzyfnwjLsSU2Qo7SJWcgqtIcsPWlWVvbeE7UA=,iv:bwbAmNpX6zXEVng/EIK3DdHkHw1kAyFFaXt7Fegw1cw=,tag:wN6QJ479Cj4w8/xcnE3Ksg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
