services:
    certbot:
        image: ENC[AES256_GCM,data:5PnqhzpaAYNQnp+tMnDy39CwAnsM9g==,iv:kYX5LKkSTsjlWCHwepatUdCstLFpOD9nV4rCjakEqWY=,tag:bshGp5yVj+9DlJeqhdYAMA==,type:str]
        volumes:
            - ENC[AES256_GCM,data:sAmSF6H8Uk/bS/DyzXGFwoH4K1effLN5ONrtBNA8,iv:jqpGskko+u8aSGMEMgoMvaB1AEAb8PuXd+BSBwg7/r8=,tag:+UoDkiOIf9eCS5HBner8Ag==,type:str]
            - ENC[AES256_GCM,data:EocPxhZcl/ANKwGZnUfoLcsVd5Z1UPkU2YKTcY4jAqn0pKsk+c/zRw==,iv:bfFZFtyjouxEB94E0E+2sLHbSjldvgzev70sc18TyJI=,tag:WgAHKjHjVC75RD3+lCk0/g==,type:str]
        command: ENC[AES256_GCM,data:npUs0b4Tf+O+0UfERtpP4sd/lqO7qlFbyowoL8fwvl32Qs8e/CBKwRaQnR2IQBu51HE8KfgReTPz9t6/CXcSrRaLUJMx757HtLHOJejSbztMaODDJCW2YelphbdfouFaIPZ6xNNImGKyCgmxeWg6EkFigZZ1Keghp8PygNDZRxMdL0LrpqAIuJ+spTwogsSQufqwpANeMtSS8wMF5X89TSS1MKgDFWRaKOu+BQvdTwAnwp4gyz2wm8vpQLlSCUuDvPLZli6o1pYPibB//aYlymvY0aZfNpiWkn5Nk3nLayzAYQFYca3e,iv:BrFjzvF/upF7eFBKwTz1LSJ6DPQp1Ehl4vG/IBTLqME=,tag:l6UemI4GVLMa9qis8l9esQ==,type:str]
        networks:
            - ENC[AES256_GCM,data:q3YvKQ==,iv:AEx7SAAbofKZwGIF+UdsgZpB4eQL8dGWB/n80Rb0avE=,tag:jpxsy6Yzo4FZpu1k9aLxsQ==,type:str]
networks:
    cert:
        driver: ENC[AES256_GCM,data:PcDAYfLR,iv:9xdgkLQjgHvygkkoo+DfJvTJ9tQk8gMAxCstSdJJqjg=,tag:+gsrelW9l63N1OSrbYY2Rg==,type:str]
sops:
    age:
        - recipient: age1873xyakw74p6jlcrausq0e9mmh5ch5en2l3nlg6a8d2qtxxmkqdqthddvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Q0crYmY5clFsRG95MU1v
            REtEMVhqWWQ0YnVWcUt2OVdOb2VuWElyZmlRCmlBUHZtUmxmWFlZUzYwa3A3REpB
            TGg4cXgvUjdZcjN0VDBTbXFXaHFZb3MKLS0tIEJzc2Nlc3N4WWlpbVlpbjh3STZx
            U0V4OE1VdWxxR0pKNVpDSlBtUG55OTQKMM5gId88okVSEPVzT48G66Wbzr/3WdrY
            w0Mfm0yhCiVC/kkjeVzIPPWUhAr6TqTl53ZISPCxknEwo0lxJox1rg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1helrvdx65wx4e7sauvut57nc288ycth5884mvxag2kmrguvgtfnqayy8uw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbXY3ZjhHM2dqdm5HQnMv
            cDNqQlFRV3VnRDBBZXZSRXBnamdFZUlwN1NrClIwbTRyM1Q4VFJTcTdyM2Jta1hj
            eUI1YlB0bkdjZFNnd0FJV0JCZ2tCTXcKLS0tIDNXbitxM3VPczM2cTBpRmZ6VzRR
            SlRmL3VrOUpVRW93OEd4emtrTkhuWG8K3Npk69ezJxhU1prccNb0oJz7CNMyDw5F
            bfkDCHvSClUiMK5W4uNKrrJZ5bN7/pQ7zPM8Cf64tE0IBo+VscalyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-18T14:57:26Z"
    mac: ENC[AES256_GCM,data:PqSFN9YhVtcU/DXEKnIUY3lT8TyVhynTIREjSdBYVYEY+6nrcDGqxP8RdBH95xth68/gimnZTdV3FX6RhRmMkMb+Dk1SC/kjaP2GHIAhpsClQPkj3VqkchY6DR6ur0BnHIIJl87TfQjaG7D5r9k9+Df0AnlarJQl+Z69Llege6s=,iv:2HlZcVWT2F2dbrjTVvUZSAGP56sMgSrcuLse2MHBjqw=,tag:dXlezeGfy5cdBvnSTlsKLw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
