services:
    certbot:
        image: ENC[AES256_GCM,data:wUjHGbv2a2sqLh50jgV7n0kz43rhPg==,iv:1916eyew6m7JQ5CW4qCue5Ly9mOpyHKF8fHrXFGaXBY=,tag:SRqCCfstVlb1/bFGTZ6V1w==,type:str]
        volumes:
            - ENC[AES256_GCM,data:P7dCKHiimC8Adj3/Las9hhcxisSMbE3PLlI5oVh0,iv:zeQ3LviFZVmnAybSJhWVRA9sM3MGHWmCu0NGIo6uvYY=,tag:RomfhjZ9GwICnBkNMgii/A==,type:str]
            - ENC[AES256_GCM,data:IuDHccIMeVSGykAqNEH0/NeQteUPUF3Mg5SAGUThxcmr8KCyVEZpGA==,iv:b8nUucKbbHmL7n/8hIDiJuIgFis+tnZVDuJB1XvaMP4=,tag:UU58tTMieIiLMewj+EPWHA==,type:str]
        command: ENC[AES256_GCM,data:7fspz6t9Q5sUNSFUok+eVEmXUmmue2KN5fyMOW2dB5199vF1BWkJGblKOHzwjrzT1ltd9yzSfJSeEq67nNkQUT5RMXJB2qbD/zvP+CrAQm/eCTotWQ/eFyLPt2PnTibRNkmyPRMeh68XDw6uzq2/uJg3JwZAm0rZsJ+vgGONo6Qme0LxrSw8/96KlugzELFDy7Pd3izW9SjBD53eK1DNmx9G8ivEmVDQh+3rVijTlxp0YiBnztixZGTXJXJmN5G/m3u5YA0K6cqmKHbRNMzKKDIwuGEhWGdOPnCZ3+qeWbaLTk/DMluc,iv:Cn9SEWKrboqZnq4HknpGtD1+cMvpv+O5IQFXqQhjLvc=,tag:1cIWkhy5xg8nypwzl0IcWw==,type:str]
        networks:
            - ENC[AES256_GCM,data:k03DxA==,iv:+HsAVrnfuWSFOIxuJ6Pn5XUz30N1cOL4wGs+ha8uzFU=,tag:XBQoCacTu/rhB9d5t4fDZQ==,type:str]
networks:
    cert:
        driver: ENC[AES256_GCM,data:K5ndui76,iv:ThhRtwQnsdjyTelt/ZEVspZ2XwRWZMambCyytA4kIRA=,tag:r85h4rCcp2Lnvfhu+XOc4g==,type:str]
sops:
    age:
        - recipient: age1873xyakw74p6jlcrausq0e9mmh5ch5en2l3nlg6a8d2qtxxmkqdqthddvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTy8zdWU1MFZsRGZnZjdN
            K1gwZ0J6SDd5aFVoa3QxOXBOZGljMTBYT0dVClBxVVB6a1c5OGpGd3drNHE1c2sx
            SjR4VFhJT2RVNW5KMDljRWFxSHpIVXMKLS0tIGVzWW1QYzc4dnJPbFdMZmNwYjAx
            czlFY201T0ZQNFJhc3NJZ1hXV0ROWEUKeXFYG4N2Y27YLopC6xVw7yylIQo2Z6aX
            ch7t3+Ft3OJmh/kS/NCD8p4t3b+l579b1IQmFX2TZcNPA3REgK6Nmg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1helrvdx65wx4e7sauvut57nc288ycth5884mvxag2kmrguvgtfnqayy8uw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Z01aNlk5TExvRlN4cHY4
            dG1Qak92S2hsUHAwNE10TTU5MzFMcUpwRVRZCjRvd2xRZkt4eEVjUWtxT3pRRFNh
            dDBrQ0V5K1E5NzBUVkx1NjQ4OC9la3cKLS0tIGR1NUNpaVBOL05rTDZ1bGNNMG9u
            YTVUQmdJTjlHZ0tEWUgyUUlKbm5pY1EKq8P1qzysHDHEnScAQZg+k8wZOHOGFcXY
            ADxBK04d7LlWyILCIJG499c34c3Yfw4UY4qO58zNmIoHwlU4g0An7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-19T04:01:20Z"
    mac: ENC[AES256_GCM,data:AUVLvPiLAm1Rl/4LaS8iZVi+cRucrJTPcdyDIcy6yflUq30XcbdRDrwsjsPX8ogK4wfQzUBA/1PzchUAq8gq3qIKrHWImKpLFZ5iDaqWU77eWL/w2Zebl8GJBI2DlM1aw8YZ8BFkqGenPPDy8/z8hkTy7HZ8ZgsBD5XGEawsqpk=,iv:RQMMSvG/AX8LiW3wvx/RpEkURtCy6XkxDW40OnZ8OAo=,tag:SQCixACkXK71VVv4TZtPNg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
