services:
    certbot:
        image: ENC[AES256_GCM,data:JEu+pPE9ykdgCanUties9f+DpwNjGg==,iv:Pg57dad/nEKqQTg7GJOwzM2IvQ51l9y3njAZ/Mq5wNI=,tag:T+dGDACLXMpfItw+xBJgVg==,type:str]
        volumes:
            - ENC[AES256_GCM,data:5DhjIfE2IYbxeS9LH/yHIkdmbkZjcvlicO1XdEPZ,iv:7deHWq+vbuWiEWa5GJHdxb8B/9jWLFxKofjnJFXbEos=,tag:S5uGiqplzkMQJszHRdunmg==,type:str]
            - ENC[AES256_GCM,data:qu8xDs90hHLHt+L1yisgicKCJf2Yn4HbXH7FEtcgXT3kiNYTHuiC7A==,iv:XB9KuHM862vIo1uFMgsG88Ce9VaHkv+n8HGy5pbmfQ4=,tag:PqKYeWLHfRgwgo5FDqUo0g==,type:str]
        command: ENC[AES256_GCM,data:zCk7bxFVLdDzw1Bk3DQipx9Wz3buHcdOhtU1p378SVAuqUqdYHJURkmFht07VvgHjavBIOXp2LhlsMtGGGRrl6c/o1YQnPrKncUmc1V0PPbbsmQLasWcd5kQAd6buDZQ9SRHvfTAEORWd/g0rSQMxeWpk2FUHkDCf60Y6Ks3ZNnyhFwVxXa9O5M0INeMbFYg+WJQqLoxRwRiE79alf3vT3T9pkYIe3Ma0Ih/GrHgCTt/JN9sgA5d/Nyz3DqnQyy1LNGLsHNgQ1qG0n6PxFiOkJfzY3X2tHcW4k5znef5di8ui0ozNfks,iv:uZBltAs+9aFMFoSqdSrtosI7wuhOYesK+zJenmaNphM=,tag:Iw4pjRBumV6FOy1+iNq8Kg==,type:str]
        networks:
            - ENC[AES256_GCM,data:lR88gQ==,iv:sMthZ2d8Vl+3o/lmvbeNqdMbU/THk8vMCan8/MODWoo=,tag:zRFB2fnt9G2GhvAHvWputw==,type:str]
networks:
    cert:
        driver: ENC[AES256_GCM,data:MFSdIHdH,iv:hYw5UYnlcrkYixIDRmcp1z1gREjH/RW1sM2MTn1aeto=,tag:BAJdSIoqWuBKIeFLJ8yMJA==,type:str]
sops:
    age:
        - recipient: age1873xyakw74p6jlcrausq0e9mmh5ch5en2l3nlg6a8d2qtxxmkqdqthddvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M0RYcVBQNE5aUmEzYmF2
            alJlL1o1WXVKaTZYbm4zdXhCaWZiS3daekNrCkhReFIwN1BBRkJSZ0FoYmZ6cTBB
            OGFKUDhOUFIzVU9xcndTL2JOd25WZ1kKLS0tIHh3M2RCbmJLWlAvRXA4MW1jSEp1
            NDMweTNXckM2aEZLMVVucVBacnN3WFEKFyEJndQZlHMydXn/kZPNKOj0dmKn++8E
            3DzVdbgxOkIwWLJ6KoNPn7o9KTpxrtx915QPb5TWRpHRAAbpWEtknA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1helrvdx65wx4e7sauvut57nc288ycth5884mvxag2kmrguvgtfnqayy8uw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWFNXWFlwdFJwUWg1YjBX
            dEFiUTVSTisrd01LQ3hTbkZoZTNZbVNPYmt3ClB0dE5IRUpCUitmaUQra3Iwb1Ax
            dWhmQTBYUysxZFlQcmtZOUlralBIdE0KLS0tICs2dzNkNEVpU2lZcGNhSWpEM3hZ
            OXFvQW9JUXNSNmpmSGNlZ2U5MUF5MUUKpKZwvj+8j2bbuyx2PL6kaTkY3K4YMuv5
            WIVs3UGkaLn9JdnCsZnMGNn/B2RZu/L4Q1gnCyGFKmiwZD6r+/OdKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T16:12:02Z"
    mac: ENC[AES256_GCM,data:kjhzKGTaUWVE+sRNStIEeEROCRJ6ElpAbzKtPMp7VltC6STL3RmdiotGimG0IJ5UgjKS5+cYcpYuVv43aBK83gaMNpOdSsYq4hVfXQfO29I3TPJKjdPCtZZDh1oSzDy0Pj5875wKIF/1ImPsDyMHmjT6Y9lAqsrBuTCsS3cYkcE=,iv:KSQRkyqDX8bKp5XtalfEtB5yULtqxaZ39TiI5skKP6I=,tag:Rs3qy2gOkyZkynnYulf0gQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
