services:
    certbot:
        image: ENC[AES256_GCM,data:8AaxMr+BzTyfHeKDIq1Zw4Z7BcvXkg==,iv:IXDyHXLyaQ+Z5SzpPLGZeDPJjmRDpcdGP3dEfh1TohY=,tag:vlLyl7N/fZ4GGClHNnd/mQ==,type:str]
        volumes:
            - ENC[AES256_GCM,data:MDfT1SC4PCZwFGPCjWxf+ye7MxBGhgTUi6J5g9J6,iv:ok6hjJ8fsoCfcZ+9yjsGbq1fIyP7axR9aHGU40WVa2w=,tag:sp4rXzI4v0gomzGW6gGBhQ==,type:str]
            - ENC[AES256_GCM,data:ILxdC7kocdZLISWm/mtMci8x4Ln0v5rz1PfYETqwXnRn3JUyVDe6tA==,iv:j1W9LhnFVWYduGmL1Zxe5CRkCnA+d52tdIyEekD9N0g=,tag:KeoArs+FDNUepGk9ja73/w==,type:str]
        command: ENC[AES256_GCM,data:6pvortehnGG5vLieGeNHRwieq3M5psocv0B6tQ2kViFcDW9uaHSmocq9nd2cpvsGX2uE9wOe1ZcPtKTStcVfSIHFWhUMxyIhTo3b+ktkoikSIdDzcnh9bHkDcQVQl6GNL9GHuzOEdH4E5bo4mzLgsHG1Eih5W3EU3kj1fe0IsFxzUZxeFobRaifEHZSPqVRgolmiE9yfdb8gpkSbSS0BNzIRk8LAQWyZrc6bkG2zlpdA97kSF6GBaRtKpWI1E97Ox4HxAxFn1qFzOxC/GZTQjlabo3ouRZ5DtlH/Td3jv5Kzi5BtcXyM,iv:C/lAQU6jqbImmkGMAxUbrRDe5Dib9Lnm0+w/obgdTN0=,tag:No8bcoVt7wIYGaYzI2b5BQ==,type:str]
        networks:
            - ENC[AES256_GCM,data:Q+rv2Q==,iv:sugXTFuU8VXWXkykELgcCmyECSnCbdyPXwy1RkPwNC0=,tag:F6J08o8gtGXGI6G5Vix3Zw==,type:str]
networks:
    cert:
        driver: ENC[AES256_GCM,data:BkytVwnV,iv:X+yvIulXnObv1L+qhI/hzsqyItwzclv8GmwSPZRb7cc=,tag:57Q8inzhzP91ansBoN6h/g==,type:str]
sops:
    age:
        - recipient: age1873xyakw74p6jlcrausq0e9mmh5ch5en2l3nlg6a8d2qtxxmkqdqthddvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQW1kK1k2S1NJMnFja0pz
            SWtrbnFDSU9jM1BDdDFObnplRGc4Q1lKdTBvCkVXMHJlKzU2MWlWeGRDNGNZMUQz
            d3BFd0RNY082LzRmMHE3Q0p3dGkvZWMKLS0tIG5XdVVKeUd0N0dHOFk1SklLU1dH
            SVhWQ2dEbVA5RGU3aG5HcWZHUUwrME0K1qpUUD+sBN7ISFODQrxyTrWdb/9zoXXt
            8/g2KkzmCl7PCbXTFk0n9cN+QlS8ex4uyrQecVJnYmH1C44FftSe8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1helrvdx65wx4e7sauvut57nc288ycth5884mvxag2kmrguvgtfnqayy8uw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRnY0RkR0MG5KMTZESlQ5
            SGlyRmVEaVdKbGJQWFN3Nm5DWnNXL094VWc4CjNlaTVHRElHNWk0TTAwZFE1Q0hp
            VnNoeHNVSTloUWhDQTlPb0JFVG1OTkEKLS0tIDg4QUs5cEpLMFBaNDRFT1l6bXhs
            MkVDSTh6ZW16WVNCL2oyZFVjUlBIWUkKvOTXG7T/CKpcMqwJTlIDrJh2XjA7Ir+7
            VuKsSfMIgAMaiSlv4YQ4I1chc17EH+43my89VGbel3VyiIuvY8ZYsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T04:59:57Z"
    mac: ENC[AES256_GCM,data:FskoBbcZvU9BENuiWlNG6L+43u5/crvkrkY6A2/6iJ4rNKxTM+l1+GwmVGR3bjKDRUVpxlw3/gGrF8Wjvg3ss9KIlUTUSjRFQzYZS5imvgRA0+QXOTYEh4RMDEeM9wbE4HF+V7M9Hllo0Ai3t4dKm1GoYEekZvvi70utBsAIrAA=,iv:0YOOGryzi0Q+QqzroMgZCUhaC2g0GfchdjNn0RNANdY=,tag:pfnXvrsSKIlfWQO0ZGgP9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
