services:
    certbot:
        image: ENC[AES256_GCM,data:I9hlzhEQzqNEoUgPZIS0/MuuYDdRMg==,iv:H1t0lg0aLgnqHqtqXY7bVicuZxRgdML1+Iu/ElHHugQ=,tag:8+oxt+jNyzE86nsd+bZ84w==,type:str]
        volumes:
            - ENC[AES256_GCM,data:7Kw0PQhbj8fS1dWT0kH7sWr9fBbgzW9IdphXd5iQ,iv:UcJFQSC2WHQpHe88wV7tMzAEzNYmZbvBYojV4WoptcQ=,tag:PacJAxsfDCPQMXd+6MClMw==,type:str]
            - ENC[AES256_GCM,data:9l4amEHmqOeDE9AlNd4Jf9mWBUf+Xn4Nt3ppwRE5MrEl6iVZ0OKvmw==,iv:7Z6uU2VO/OUISvTFsrzx5gqFWCJAWmfWryZ/8HKTKXc=,tag:W9fMLUTv/cy78HgkEGW7Iw==,type:str]
        command: ENC[AES256_GCM,data:px3u+/Xx5QJcK1XxVDdUKw2e15Bf2BRvfC0VJ9NaRphHLn5cpF0d+UrvuYbxPnfF3wy/893cXwXskwbLOuUavxtNkJ0aawHV6Gx4FrrZRU3YbhoaH9fxHjqW3Izz6zQwIkQi1ZbS7ox5HDXtruehv+sIkUkzHbWpOX0TxijBnEDXq/V6dz0FJ+t96Dw12jwT+1yob6rEqttrnsslulrLQobWTV0JJTvgEM3JAygvXPt0nuNWZSyMna5TfVelppak1fFu2NUuErZZgT7TAjKq0vVvP9Tn1nYX7J78u4cn/A1wPAV+/S0o,iv:Hi42m7fTowsC8UR0F0Wt7jwsyDYz6jLnmGKMfJdW8k4=,tag:8gcMoAcHlHAcWIwcEgPhxw==,type:str]
        networks:
            - ENC[AES256_GCM,data:t14z5w==,iv:5urPlNTGc69IMzSURaY6EXoquFDFD98pYmeLrpiu5qE=,tag:RTWZnq+0joZwOYlJEkq0Dw==,type:str]
networks:
    cert:
        driver: ENC[AES256_GCM,data:Gwaqv4K0,iv:llPTykXa7unB1ajuhE141hzFZW3fkT0cFH1vh9Ky2xQ=,tag:iUiYGmzra5t2p1cexe2YmQ==,type:str]
sops:
    age:
        - recipient: age1873xyakw74p6jlcrausq0e9mmh5ch5en2l3nlg6a8d2qtxxmkqdqthddvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTnJjU25sTGViY3l0MHdV
            VVdQQlB5N1k4WVZhZ2xkWm12NTBxVDkwUUNBCnlQQ1NhOWVyK0R6amJrb1hpcklo
            ZFUrKzFPTURGWjBVOFBzeFVQUWpWQXcKLS0tIEVVK3dQMEdJQkg1ejQxMVViLzlF
            Z1RMSXZqK25qMzI3ZHVUSmlKUDZtSUEKwQzmQ+D/GpGabBsehZzwqLj8P7AFNfso
            c11EYczvboRs15EradStXL7g5atEJDNrBaDECq29OPpisB4GwcL5Cw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1helrvdx65wx4e7sauvut57nc288ycth5884mvxag2kmrguvgtfnqayy8uw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTUQ2M0hoaldyc3NtMjNX
            S0lLUjdoMUdBYUNVY2FJOXIrNng1N0ZTY3dNCkFwSHdvYnhaS3VUaWh3WE5hYmIz
            blNDOThVWnJWVFdnN2wyWW9JV2Z6THcKLS0tIG1XdEYxenVjbVR2dkRTUkN1bVpL
            Z3p0UXl4RUNwT3Y5UmFMMmFHaFE2cEEKG+UChaqeLcVcuklQf5NQqwE3lx3ilgkj
            Jq1x3PuVreMOEvZ3rF4u2MIb+Gts3T3ZGAUjETn4nXQ9g1kUoP5Ldw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-23T04:38:01Z"
    mac: ENC[AES256_GCM,data:txDH0dkVYSpsiu45pGNDIRH2oJXhb5OTnv2Qn2swYCuSTYe8S1dlBlfu0htFphslk1aURciYqhdGMMyWKvpFqM/VjMhEMjAYmOw3mJW5TcIga9gBODwvuuMYgrSwsa4i7rmoD85phxy645qjjLPOENLbe6DgXtcsCPB+nRvg4gM=,iv:q2wrt4FNMtqKbEAoDWqy4DlRVBs7WX3LHDSh+ufB+Fw=,tag:yDYwjr0sA4UCo9dpugnO0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
