services:
    certbot:
        image: ENC[AES256_GCM,data:1joqajdxs0lIt5Kx0/tFmTtq+zsf1A==,iv:AL3Th/lM4p613/mdchWor7IW3muop+myA4tzfJhywOA=,tag:KcdaoC+d33W/GOSkMKrFWw==,type:str]
        volumes:
            - ENC[AES256_GCM,data:Olm6A1BmWmpXG81BpKLtQ3wtMT2wZHhYJCOuJu+a,iv:+05JniRdFavODhxf+rwFz1Jq4KE0nt8Di9hcLZmwFC4=,tag:yuTexVKY0MF/1Rx3Z622ww==,type:str]
            - ENC[AES256_GCM,data:013C1m+R02Pj6YDiAEsebIT757X8ayvc//1aPq5d9ypZlXwLY5OllA==,iv:2yrTL0st7q/kutb9yZTT4RGo0udBQ1TiGP6DsvXR7SE=,tag:qBLkindYV8+q1LLtUJAOSQ==,type:str]
        command: ENC[AES256_GCM,data:/tU4btSA8q215THMo1ya5g3GCTBrrl/r+Uc9PAPTaPtiSRoBBJvEOvnlxFE5e9ZpYka2BYlJwQZdU9Kr+vGiXVNPeSuSscTHup3YER+jOP/0u9WTjbEfOLtewkQJkhLHMljgNX/9o6TqKGJoCyzSDs/PRRmmkMCqoEZ9BMbK6Y2hBFRBpFzKBAU7IimGT1DLIDprx4FtiGeXbJWz83aNRk7CYuiLEx3aZaTEiM7vAncysbCGaDbjDFkBXL77y4URa+COrnkG4aoDf8/GgWjTPrYiSKOut0AFD/eZdNyqC7Uj7N+XyijI,iv:o37LY/seZA0kD8We4Plm2wtcZO8zDPZEJ3/hmEf2vmo=,tag:ZE9/PHiRdWlMpYhs8EMACw==,type:str]
        networks:
            - ENC[AES256_GCM,data:U8o7/g==,iv:yf/KqvTPZYVNaDboGwTaXTFmOUWSRpRj14DbhMO7tIg=,tag:7dqHH+nqbpTMOGBZuWPyCw==,type:str]
networks:
    cert:
        driver: ENC[AES256_GCM,data:UjXVD5+G,iv:iQ2dZ32XyFVD5foy+ZDvnDz/yHkFwkIMcU5yFirKM8M=,tag:nRoRlzEjAfF9FcVmtzt8RQ==,type:str]
sops:
    age:
        - recipient: age1873xyakw74p6jlcrausq0e9mmh5ch5en2l3nlg6a8d2qtxxmkqdqthddvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNFJGN1h3YmM0WlNqaXdQ
            Y2hrN3JkRzdYdTFZcmFPTzVuaFZqbGo4SVYwCmxndkY1L09UdENNbktOQkdGaDRM
            eWlKWjdzNW1kZDY1RFlnSHNUWlJiMGsKLS0tIFJBd2lqVTJZbkpTdlFHZW9pbGZC
            RmlQa0ZMeUtqcDROcURLbnZsZ1RGNFkKWmzDnMrRFVl+QDfY6aFStWgSJFqt1jEG
            CWM1jSXC9ZaBWuGhkbHBvfjkivSsXf9WwGCZihIadE2XH4M6TPGOeg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1helrvdx65wx4e7sauvut57nc288ycth5884mvxag2kmrguvgtfnqayy8uw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2S1ZqSFQ5cGI5SjF2TW9Y
            eXVMNDNxeUkwRmUwYkNkNGo0L0poWWloMEhJCnZLOVJpdTdmOXBRM0JaOVNvSlEv
            bU5DMHFmcjA2UmE4UDJuc3JoWUJaRWMKLS0tIEN3OHZOMy9oMzlHS3RmWnAvV245
            b0J4aThsUk9XUTRSY1JabW5Oek54WGsKRXlt9pM0CPYBE9aJlA/HgNeX8EKD21xy
            km+UDcA8/1M8wztKzQNCuLjv4Clz9w6mvlSCnic0GWdBWlXeyDnNpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-18T15:33:22Z"
    mac: ENC[AES256_GCM,data:sun4o9RAK0Drv3kBPV5EaFrsYL29otjyNjU0G+3CcFDPlwt3DmAS80t9mPVuTGbNlQdNeOx+kqn95cmmlo1wj1ZxF6OQUoEJir/cFP/nRx16GzTQqg6THQgnd1+dxvI53IRjEXJkFZoeXQ+Zn15NI6Wp5VhFM8CSO9rII+Bitlg=,iv:5qKfrVyNRmoMorCxdqHEpHe9FWJW/viAFVP7G4YFDqk=,tag:0WQqGtF1VZ6SP+GW/v7ihQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
