services:
    redis:
        image: ENC[AES256_GCM,data:s2oWmWyMPjy3Q/4+YNBfb9hR,iv:fIuZEc7tKXav0DDF8GVqRkNDRb8YIzkD4Va67BPljPo=,tag:MkyJk/6a4sZUfC+ADbSJow==,type:str]
        expose:
            - ENC[AES256_GCM,data:Hgk5jBaDSQ==,iv:21+u8E430xCZPQya6qOV25M8bdIt72AWrWvZSexhsuk=,tag:7dCq4SGPPCBs27yhYaS7Ug==,type:str]
        environment:
            PORT: ENC[AES256_GCM,data:/ejhgw==,iv:g+VaVx3wb/x1jdFnLdps8cqYDbYmadG3zUonDfeGuv8=,tag:3OSIPWX/xZm8spy49IvkYQ==,type:int]
    celery-worker:
        build:
            context: ENC[AES256_GCM,data:3R5gtXZmb7M4zw==,iv:e8MonBWsskDqPAmlp/0jqwXudEYJ5/YH+9nyw78/S54=,tag:zD1cuuPRYXaJD1cU5HUrOA==,type:str]
            dockerfile: ENC[AES256_GCM,data:upnRy1/mqf4w8MIItcvq1wDbF9bfbGxSk0d2kOE=,iv:WBZBe9vAuK/jRe3eV2KY0VjTAoCHo+QqE6lr8Cv/fS8=,tag:Q5/rmh9GQYmcG9oGq25FHQ==,type:str]
        environment:
            REDIS_PORT: ENC[AES256_GCM,data:O6HCZA==,iv:Jq3ZsSo/t5JdG6d56IKNNA2PLULvgMq/AvFfGbRZR0A=,tag:oT00Oq9CV81QyVKH4hFb9Q==,type:int]
        command:
            - ENC[AES256_GCM,data:eLY=,iv:sRABl3OWg6jKOkUoZgd5j1JWvibZp39TkRDDmAh4jy4=,tag:wUJpWs50l55Eqb4ueB92VA==,type:str]
            - ENC[AES256_GCM,data:UNy7,iv:WEUHGIzcJEwiYSRBUtzhpOVhboS/OENgRwghoQRfKng=,tag:0Yfbpl2yyEoFXWxcCs35wQ==,type:str]
            - ENC[AES256_GCM,data:PtckQNs1,iv:3xT4qRlr3ZNXc+dGN9u1VMb0L3wfGgp2Axf4hkjY0v8=,tag:1E7bk5jK9d2Xz1Y2C5D6Pw==,type:str]
            - ENC[AES256_GCM,data:B40=,iv:GEIvhN8Iqzfu+a737tbZ3yUibZ1EzeTg4PLCAb6KqV4=,tag:6MFz577rNUPR/siyOOs5pg==,type:str]
            - ENC[AES256_GCM,data:0/EzyOCtAtlL/MBP/SRxpud27B5bB7fNCG/O08E=,iv:kvMTIt1Q4hTZK465PqD32M3fSpgpiPLzB2SPta3QU1c=,tag:ZBdq3oxTkMeFpZszR0COiA==,type:str]
            - ENC[AES256_GCM,data:n1mr/t1x,iv:j54VV9mhBrLmGA5PdmiAvYqyX3RL2LlF4o3eyj8WYw8=,tag:XwFdbQyr79ZBYTMVYDdPzw==,type:str]
            - ENC[AES256_GCM,data:YT1D1nW+2cUsE4gVD0h5,iv:v+2hTgdWE2/Vgmx+4cUBhJOkxOvTUo9TxFzdC2hYbsw=,tag:wcG+NdZlylxk7IBnHTSEcA==,type:str]
        depends_on:
            - ENC[AES256_GCM,data:GR40EOo=,iv:Xiz433SpOuVAfLryeXI89FETmJt8m0rf+zaayNJ2F30=,tag:6uj2kbr3t32FFQfcXyLOpw==,type:str]
    api:
        build:
            context: ENC[AES256_GCM,data:15XCS50FOwkhKw==,iv:O4PGrZcsE7w9BwMp59WSCgLXzD1W9TcozFhA/GulPyQ=,tag:TM6e0hCe3ocjcAlEDZBlWw==,type:str]
            dockerfile: ENC[AES256_GCM,data:CQdY2bK/8k/BArtx9nG824ZOlXn+Pkg9e1oDvZQ=,iv:P+YL9Zwz5hP+Ue8S11+kM7wBdD3jaVb1n/u0NtSQI4E=,tag:BT8hosubCdoXt6a3MKx+yQ==,type:str]
        expose:
            - ENC[AES256_GCM,data:wEtLVWEPSA==,iv:8+GJKenXhTVZf6+1fCCEFJj7TOWgWjvgUxR4E/th4sU=,tag:6ysyw2hgxakoe1CdtPcqMw==,type:str]
        environment:
            PORT: ENC[AES256_GCM,data:1n6pBQ==,iv:01f+ouEvsQkPM/2Y+i6PRfBLxLi9HbIrLiWT0TZlIk0=,tag:GpJIpo1b3kVifgfjB/MXpw==,type:int]
            REDIS_PORT: ENC[AES256_GCM,data:I1lATQ==,iv:JkSrM5njeivDtow4b5QiaB65f1+T8DoKECiAqnKJ2q8=,tag:YhZc59Atn68zPknlCG3WyQ==,type:int]
        command:
            - ENC[AES256_GCM,data:hZ4=,iv:IKQQfUvkWMqPS1ItLZQRE1wQ1DMtG+6QGDlf6wD9QVM=,tag:XItG19EnVBexm/T17pocqg==,type:str]
            - ENC[AES256_GCM,data:sDdM,iv:VO0SO3EgqQVhojEpGsZQofSIk2yzfLMgG6xCRy8ng2U=,tag:nUyHHpl5BnaTw9ovlj/6gg==,type:str]
            - ENC[AES256_GCM,data:srUGyazGAQ==,iv:Z4/xqxxWqcDQg+Z1OGM69P/mvaw0vRWrJBXLjNN5OQE=,tag:Uqq59HCHThHXCu8jWpNv9Q==,type:str]
            - ENC[AES256_GCM,data:flnb,iv:YUosk4St1KsyMioZQuWwmesl2qkqNj71eF4srN9cr6g=,tag:7BIUzXhO4J+lGDmuc39rJA==,type:str]
            - ENC[AES256_GCM,data:Ao4jO7zZmQ==,iv:8Ke1g5NGv7Pmp/xdk3ZGTy5qc2A4omHo5dmA+y9Pnjk=,tag:MMgrxXweOjRG+Ov8S8ryug==,type:str]
        depends_on:
            - ENC[AES256_GCM,data:4Hx3SeJUicCUksHIGg==,iv:wXfe/3Wcg37igr9sGGAeiOL7OaeiDDZlbPWqckmhjyA=,tag:p88Wq3z78O2X6cvz0HAo/Q==,type:str]
    web:
        build:
            context: ENC[AES256_GCM,data:ClZ9/oZE,iv:ONHw226ENCLdUcSRgtFZGr9JK7KVO5nh8EAYgrPNZWs=,tag:rHTIXxmnr5zYiGlxYnFzFw==,type:str]
            dockerfile: ENC[AES256_GCM,data:XzJcyh6Ny+eLloSdV4AwkPOcUutwS5S4ew==,iv:uPTnP2LTUJajQkhCuEaEtlVC5NqCtAiWnJjt9HjCXJM=,tag:wQqeAghMQH960toNmj2d2w==,type:str]
            args:
                VITE_PORT: ENC[AES256_GCM,data:GBAG8A==,iv:sQ8UEwLXgzsCG8qBlWKYIBcUvqCAIRbFABgfUMQyyOg=,tag:qomRpUrnLhR7ZpX2apteaQ==,type:int]
                VITE_API_PORT: ENC[AES256_GCM,data:0MBVlg==,iv:9kdrPCTKaij2DAcC1MZqxZhK+Hixy+MlVDH+z8kRADg=,tag:AcC+CbY2ym0U5YuGeEfXZQ==,type:int]
                VITE_ALLOWED_HOST: ENC[AES256_GCM,data:VBwrREhT4Af+HiV70FsBFrGu,iv:wLnviyFeiEUFKsHLfiG3+9dcKpiP9P0JXfkn10fu8t0=,tag:AM/0LZ5z1K8r1iNvRgtssQ==,type:str]
                VITE_HOST: ENC[AES256_GCM,data:RJHgo0aeRg==,iv:LWGb32uHmcTJcrZiHaCbkxCegYGX5xW9pgVrzUbVR2A=,tag:DpyZSFy+ttgX1VY/n1STaw==,type:str]
        expose:
            - ENC[AES256_GCM,data:foo7CU8SOg==,iv:yzF4wUnU/uS5rcUcTTh4zNWthOvTvY3f6d+vZrgq6cg=,tag:4xvMvn430dvXTeHeBFXe0w==,type:str]
        depends_on:
            - ENC[AES256_GCM,data:vRO5,iv:iL3xJJ7QNVf72Gi83xdTllizGGB/8k4YcBcZGqL4FA0=,tag:odq9inb/mGcjG+aok1Jj8w==,type:str]
        command:
            - ENC[AES256_GCM,data:0X4T,iv:lu1E9EA4iCC+TfCIHo5I0OgAqVJhBAjpg7QA7ot8xfE=,tag:3KIBMjJs/fGmhVSan+QjnA==,type:str]
            - ENC[AES256_GCM,data:pjCV,iv:FERws1eRdCYKTlqFKs+1vQKYrT9W2KfQXBH/3RN6m98=,tag:WLHjpf5XR8KYC8A4b4Rrag==,type:str]
            - ENC[AES256_GCM,data:Wrq7I/dk8A==,iv:t5GiwaJ/UQ+fdsIEL/vb5V9MEFOCNqRlDJl60HmV0QA=,tag:0yCpQ7myZsVQ0ahN0bV2Hw==,type:str]
    reverse-proxy:
        image: ENC[AES256_GCM,data:GNu2+QgrAhR+URQl9iFknOCai1Ex7R98CkwYZA==,iv:fQGcRX5vqjQxOihk3whUuFs6mOcn7H7fIGQOpJIxODE=,tag:9bJdiu+qO8nLsQI017rs4w==,type:str]
        restart: ENC[AES256_GCM,data:gOmCp1Uj,iv:guKv4gjMjfDHOYJCMfahGfKrTq+fcQYGhjwP/KFWHZI=,tag:G9aUUB8wvE2PU7fklov/UQ==,type:str]
        environment:
            SERVER_NAME: ENC[AES256_GCM,data:dV+0cBvWJkd2VbgVAU06lXiO,iv:Frl833Q+5y5wMH0fDox47o5mMZtxKw7MCu19r2HDUzk=,tag:QfX8weMmSTf6x5bVSUSNCQ==,type:str]
            API_PORT: ENC[AES256_GCM,data:6wZSnA==,iv:2EQbiAjsIStyU/apOxk23lHaH5h6HWdESc8qGW8c/Uc=,tag:bz+SDXoBgvMwo5CousXYGQ==,type:int]
            WEB_PORT: ENC[AES256_GCM,data:ejCSDg==,iv:2UhCiS7TYEcA8M8L5BGUozf+ET+EXrXLqsf1thHY9tU=,tag:Cxwql4wuzq+Pal3dTde1ow==,type:int]
        volumes:
            - ENC[AES256_GCM,data:SwHaPKJd6goxLeokF0msotlF5kKXp6BNavFWbAGBhkqiOpCPYIY=,iv:JqhFAOvdohSHswgEyjzdS1ImemF5ot8otOpBl60W8dQ=,tag:4R7ATtH5YH0NXM+ePG0arQ==,type:str]
            - ENC[AES256_GCM,data:0XgDnxrVApN3TseRLGKmC34qxswFxLEkjX9G1XzCIxHL0bVfn+s9ei5bhw==,iv:zAFn8RHRBUNnerTzS4EsxJtnIoZDKpNuP6NYs3B3jcc=,tag:LE9O9wEYR9ksaCh7jRmVeA==,type:str]
            - ENC[AES256_GCM,data:VvqkR6ii7/KzcG9TAnRvU3tVH1tHsfQv,iv:/iEqS0MFEEdbjnXYcPw1eJlxuofwXYLas9CBwrJU5BM=,tag:ss/6K+eJRJzG0ZmDuOrUdw==,type:str]
        ports:
            - ENC[AES256_GCM,data:nCxc7aw=,iv:4/gzQ3RDqXNVuYCp/ePrFWBzMAqJBLqboq+7L3HccMY=,tag:1dRRcZlqgsJUgIlAimjy1w==,type:str]
            - ENC[AES256_GCM,data:Mgf7ax0k6A==,iv:pVosDSiCDyCVEuf40XoJJQGDHO0iIXJk8HkyUMeuGRc=,tag:yJoPM3XADtVky8mnjvRw8w==,type:str]
sops:
    age:
        - recipient: age1873xyakw74p6jlcrausq0e9mmh5ch5en2l3nlg6a8d2qtxxmkqdqthddvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVFNFZHlhUE0waE1sVjhq
            cm00ZkswbldxYlJjb0grSHYvb1BLWWl0V1U0Cm9jN2g3Z0FRclgvZUtxU3VNSkJJ
            QWRsby9Jb25OWmdCWHEwa2s5YlQxTXcKLS0tIGhqb0ZXSHJyaThMdlNMVXZWSzhG
            NlFoWnJWU2g5YTYvYmpkWWFheC9PSG8KC9sUZUpNmJxHRAyTk9XUxvVCXpfQ9XYm
            Q3JY1yaBPMjFO0SEaN2dAJOlsGGiZIWmHxtNMADMfih25b4w/k23Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-02T19:06:21Z"
    mac: ENC[AES256_GCM,data:bgdJzicQ78ZCVK32L0vwFdpza9rC5QXubpIvl53B3JDv+qudKNbKMCiTTCqRGC4joSaBW/KiMhDI+lbT9PCXc6ZT1rZlK1oZsIo2UidoCcZTvF9Af5Nt3PHI/QgcTlRGlY4yLmimu+lBaMkRxtcL01hBmyKrowSLGHk3f9UWNYo=,iv:ANNqF7Ov0H8feg38aVLpSOEZJMkzWR7DGkYvTYYBXis=,tag:FpahctON6JP8ItSrBL/4jA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
