services:
    redis:
        image: ENC[AES256_GCM,data:6UIAiKy+mtr/8fjgO3+hSYq6,iv:1zkm9FlxEyf4G0zqqMQnIQGnJgZyZO20Y4xIZgwsk64=,tag:4M4KHxav5B54S3UhYdUCdg==,type:str]
        expose:
            - ENC[AES256_GCM,data:z1xf8EWnWA==,iv:RVCmiVeiSm0OiEzYmIk3sbeVdi8kOGKjhtLIzex4/DY=,tag:IpMaPqK6D/UH1ZjvDPRmwg==,type:str]
        environment:
            PORT: ENC[AES256_GCM,data:n7mAAw==,iv:x7mSADEcHC7IBc9Md8RDP0JQqieb7azt9OFQnCnzVxw=,tag:1BCrGkBuxgt1lYOT95elYg==,type:int]
    celery-worker:
        build:
            context: ENC[AES256_GCM,data:1rmLk9QtdGxTTw==,iv:qMmo+KZmtR74TBLMV8I+/ahU8VnM3o1PKAgc5j8X5tA=,tag:E1jqpg2keIVhRv4PF5IlkA==,type:str]
            dockerfile: ENC[AES256_GCM,data:2EZ4Uz0mgdACRwWgp+fKoM8bsGAWKd3L37maRAU=,iv:vt86hHPUp791SCKOzTvmFRRpOgObpv3+ujSaExs9uKA=,tag:VtlEuT24T3q++Cil8sB+1w==,type:str]
        environment:
            REDIS_PORT: ENC[AES256_GCM,data:zGWQpA==,iv:ppQ7ymTpXozYOIiEsYVe9v08utrKoI9ejcQN5uZlaGY=,tag:CDmmglBXhGwCkPSA36Ow4g==,type:int]
            REDIS_HOST: ENC[AES256_GCM,data:vuOK0ME=,iv:aOOCKZ6vGC+zYaag1kzFtkDchnEJfS4J0Bw1XfF5WTk=,tag:RTMi24FjhXGfc6BKMypStA==,type:str]
        command:
            - ENC[AES256_GCM,data:b2Q=,iv:wyPur1wS/JtVr+JpgnKr9oFvnNsOf/vOPRzgUWITGcE=,tag:VZglP2sVO99niJl46TS9oQ==,type:str]
            - ENC[AES256_GCM,data:5wlC,iv:OHkb3GMyRw754X76PXNquHe7qssrn8neq43UH9FsEKw=,tag:N/8kKHXJSrl/+9GmD577gQ==,type:str]
            - ENC[AES256_GCM,data:HxDrhhjb,iv:5E3G+XAC8XwIFz46rQTdIDXBUymnz9AWiAZ+fIeAxNg=,tag:9hjhYsbJY6DKpCHzs+NuIA==,type:str]
            - ENC[AES256_GCM,data:mno=,iv:fDtpjaU03w7L/KlER74ECvWgcU+SUEFU3o9AGytuS88=,tag:K/klPXeaAorvxUEIP+rQsg==,type:str]
            - ENC[AES256_GCM,data:UbOAzEfFEY5vIs1LRgeEzsJ09Sl1MMKq2ZA+9dg=,iv:Vu3nS/VY1mrmXsfrKXtsbk6hy5330iaTLRigbmNJxzw=,tag:6lAUsL9LN6zYvQLSwTvWYg==,type:str]
            - ENC[AES256_GCM,data:Tz/agH2C,iv:e3LimpPdwsOGIYABCWb1px98MItL7DiNA6EQ4G+UfdE=,tag:bBiEAnAOK+SCoUma8KYpIw==,type:str]
            - ENC[AES256_GCM,data:YeHPij71lMIeTz8u01CV,iv:YdQcYHIf+Xqu0PF1ikX3uPgW68N16tiKLwi46P0Zqj4=,tag:7M4Nid38hVEUsUF0+DiazA==,type:str]
        depends_on:
            - ENC[AES256_GCM,data:/uZovvE=,iv:YmMR/0ZC2iTWgRk1lsFp44YGTh1L40qVz/JMfAjiZcc=,tag:EBfBrLDpULP8ROHC0VRWRA==,type:str]
    api:
        build:
            context: ENC[AES256_GCM,data:3yEKYZvFYWHXeA==,iv:QGui42tjpvDQE8nEeIZJP0ghGIs3jZicuxr2e+NNssk=,tag:HqWnLDt2FnnTnJiKch8CAA==,type:str]
            dockerfile: ENC[AES256_GCM,data:r8FS6XEi26wGMQjSkhAmtly2w45sXWsCufen0jE=,iv:dngHSPEpYLE0xw88Fibkggll2B+1Qq06g8Fhds8GFSI=,tag:R3v08L5hmpzCLOgs/Z3iXg==,type:str]
        expose:
            - ENC[AES256_GCM,data:0pn9HASREg==,iv:Zh4uBQL1HTG5vJ2CmY1PERWg78nEpUDvuAJ762vb6Ho=,tag:o9PRKbzDs2/sSq4Anf+zhA==,type:str]
        environment:
            PORT: ENC[AES256_GCM,data:nwRLYw==,iv:iLHYbjZf4yWdGBmVcF7LayxN1tkVbgI8s2PWYoEnCgE=,tag:hDopCjtibe5GGRj+I7C08w==,type:int]
            REDIS_PORT: ENC[AES256_GCM,data:nhserQ==,iv:qhY+X6T0AmR1vz36cTnDlvJvvT0RRzF4xWthokaUkhU=,tag:ZQi2zIohJ5axbRPjQ0FUgg==,type:int]
            REDIS_HOST: ENC[AES256_GCM,data:hOUBdsw=,iv:fi7LZ+xAOjGbYOacdDqv3NISn7DbfMyGq4mZaXw7xXU=,tag:UybbcEREFBOLghSx1PEkpA==,type:str]
        command:
            - ENC[AES256_GCM,data:y4c=,iv:Mal6QA/P/99a7ylPdQMKhH+oGuGGuyMrijanGG9pXGI=,tag:vaR1KVY9YRiOFr/dKT7+Uw==,type:str]
            - ENC[AES256_GCM,data:igoT,iv:31vENXgSKlzxCeNrOFXeeqTfkycbAAGnA57glGkbk7c=,tag:gVF8MwIR7u9eIxGTUSmhHA==,type:str]
            - ENC[AES256_GCM,data:bBPQcf7+jA==,iv:fXfRdZ7sj1DWL+AUjaHsgfM+8vnLSuGZLEl9n89WMmU=,tag:P2bZ7apbsutviysFe+xVpA==,type:str]
            - ENC[AES256_GCM,data:eEWY,iv:0Ff9U+HMPj6AgMP9fGdGBu9wOiB+0NXXkF/xL3PPoPM=,tag:TaTbWfiP61Pjsr6em6SILg==,type:str]
            - ENC[AES256_GCM,data:y5ymLFgXYQ==,iv:Q78shc4nmaDECTJyg3oBHuZlRDtKh83SKZjvj5hg/bQ=,tag:+4+DKdrh0reNT4q9WSnlEg==,type:str]
        depends_on:
            - ENC[AES256_GCM,data:zDZ4hfLvORtmsVjkBQ==,iv:IMdYZ+zYYern0XCsDRjqIQrMt/60qNN/gmujVw4jfLM=,tag:10lznK4O5uJSp/0MINFpDw==,type:str]
    web:
        build:
            context: ENC[AES256_GCM,data:sVFTw0Ts,iv:FWqbMjTQBS2fr4nCU4KunmS9N2PrM8OZ3SKXjdjiLkQ=,tag:zXK+eb8a0UNGYZolJJJY+Q==,type:str]
            dockerfile: ENC[AES256_GCM,data:XasWM4r0hB3+wVV9ZvIH7DagEQw3pk+QNg==,iv:jvO424EUWp4xLoRbcnRrbsbronjs66+o28IZdrsJ5tQ=,tag:yY45XvNNbYmJk5LI9vA4qg==,type:str]
            args:
                VITE_PORT: ENC[AES256_GCM,data:nsAFAQ==,iv:FFHMSRUUqFQpvQzUah72lKaNr+6gY8Nqv8S8mhzXHXg=,tag:yUHiBeTuB/qH4HeGRnvbTg==,type:int]
                VITE_API_PORT: ENC[AES256_GCM,data:4AiUVg==,iv:bV7HhnAVm65ihwamBLdyiMJ62Bx6nVbJdXcmHp3T3Zg=,tag:yWp0t+PfTiLNCKnzF2uvFA==,type:int]
                VITE_ALLOWED_HOST: ENC[AES256_GCM,data:uKdPEwxkriuM9HCaeH5WTDX1,iv:wYXTBCH40x752K0fdIeckAZNKr1rbXXAzXe4cQR1Vtk=,tag:5jy/NuLIOAo0lSs7HZBOPA==,type:str]
                VITE_HOST: ENC[AES256_GCM,data:hlynyw0y2w==,iv:sLIB5kjk8sw9p5Md9D72JqZIGXC2S38ZF38IxbpmdL8=,tag:lyvKziQdeeqndiFfFc9tTQ==,type:str]
        expose:
            - ENC[AES256_GCM,data:wUe2+BHDEw==,iv:nImYM9e5XwpCxYcvSOSs9AEjePfga2TiMh2CQ2l8fL8=,tag:S3mRpabeir9b6oPzjpWxbg==,type:str]
        depends_on:
            - ENC[AES256_GCM,data:sg1F,iv:iuL8NIDEMPhYexyfoCs+JZG3+V/Swty33hKbXq+ppVY=,tag:0uimnx6Nk2vJkXZFnkNU2Q==,type:str]
        command:
            - ENC[AES256_GCM,data:+xw2,iv:XW1ByHesMoMkUA3Ezm9enqxZVCRZs3rOBuckCPimp64=,tag:R7m2BJQBXHdwuQIp3AgVLg==,type:str]
            - ENC[AES256_GCM,data:ext2,iv:sA0SdmoH43jCGQ9ghznxnTb2s3fvtE4KlKDT1u93KQw=,tag:WIi9cZ93mduHqcA9tk0Dcw==,type:str]
            - ENC[AES256_GCM,data:HPVLROin3g==,iv:I+eJv8esfZsRb1qdd3kYFzPye5d8mhSWO34O0/v71C8=,tag:x05tGyBTEoajCCbjOU8How==,type:str]
    reverse-proxy:
        image: ENC[AES256_GCM,data:xTJVRZh6NscPyt/d/lhss1a0CZ9NnmfhuApYLg==,iv:G8Bs4y4jod9PQn0GNVmUYjrfTRenyOpbUr8es72RqMY=,tag:XU5IBBfnSnfzVaaSS0N+Vg==,type:str]
        restart: ENC[AES256_GCM,data:O7xDsTNn,iv:Ghfu/HBZ46nNAD43sDMueXppI0xP9N69A/QoUDXWhwM=,tag:tfCJKAp1FbuBZ7uEXv0JUQ==,type:str]
        environment:
            SERVER_NAME: ENC[AES256_GCM,data:HhUZymL5wo64bKEoesHumTkM,iv:4DZuDB9yVFhcyYcpnBv2a1q9F8uz7vr39xYlz0T3Us4=,tag:suAuf1wQNH4e4IsN523Zqg==,type:str]
            API_PORT: ENC[AES256_GCM,data:uJ69JQ==,iv:QsOeyZsiyu4+tJhTbr9x49TdiAqKa+zybMuV4B88dZw=,tag:KTA6XIeIUAcNzA+QjOIhjw==,type:int]
            WEB_PORT: ENC[AES256_GCM,data:Js1Tcw==,iv:eGSu7ZevcMBXR37ChrJOJZvzZVi7fIgW8Jy2lP0c61E=,tag:jHGCzC5wd1l+eJ24qbu3xA==,type:int]
        volumes:
            - ENC[AES256_GCM,data:SBqOlkJ2V262Om87An/Bbwq4UFk9hIfyDhIHdb83J1g0x2WYpko=,iv:u1FE0/PO4vjvpyeLK67TZExoqghzu90RtHGG/9i5kYU=,tag:ql7s6nLsYVUa3WXJVXCdMQ==,type:str]
            - ENC[AES256_GCM,data:ssljc0R94PsSizKRqiQmMCGIr71C8TcBjzqh66wFm2tAV0O2c+JlZX4s7g==,iv:3kDnKlGxfVlgZrmA5mja8uDolJd/4pDcx7deB2b4ni8=,tag:fnGAPs60+sUWt7SZQLa6Fw==,type:str]
            - ENC[AES256_GCM,data:7OTdt7HXPvWZABeWXLuadop4QV0sbpOF,iv:zT6qY2bcVHdNX9K8QVscOThCoOt3Cd1SqbXqkft2ND8=,tag:AVqMT05O8oLaGbET/wi2bw==,type:str]
        ports:
            - ENC[AES256_GCM,data:fp/llaQ=,iv:dsSArWezdFJEaVRVspMTdqhEzl4jcP2931NBWpkj+1M=,tag:RYmaA6yVp3/AUF5y3H92IQ==,type:str]
            - ENC[AES256_GCM,data:a26skyDd+w==,iv:EfP9N05Ho69c5VsPm5pVEv3+tXgLOwO98XDY3vz06wU=,tag:vgUWW4kkx/OOO6xjRdDXYw==,type:str]
sops:
    age:
        - recipient: age1873xyakw74p6jlcrausq0e9mmh5ch5en2l3nlg6a8d2qtxxmkqdqthddvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYVJhRTJXVzJLVzNTOE9H
            V0hQd1YzRC9qbFlvQ0FXMlV3QktMRDRVNUNvCnJLRytWNHd5RXdLbUozWFBYWm1p
            Qll4SzRDOUVLeG5FMlc3cXhGQ21RZmsKLS0tIG5LSzk0Qjk2N0xTVVJKL3g0NW01
            SHJuNFhQZUdwdkFpNHBTV1lQOC9yUVEKEGFcoSemLtITj+M8e8YxswKhHqOkdeZx
            ZsnFn0NFtJ0Xo1qs0H4kvXzquQK0cTxyJhyp7Z++yH6WjpEzYSTiuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T12:29:08Z"
    mac: ENC[AES256_GCM,data:YCJdq+Nn7Kq7RwaeV/7n9u8up4zbKm9+rbIgxBsaAcmYhHP72Qx12R9IjaDP6ihLPN3J/Zl5IkeTcB/GeArCLFHcRs9ldrxX7WG29bAGTZiNVZi2uQ3Za/UMqrEQiv6JIlo11bzn/0H0b4jwDMEWRaoG7AA93EBNd8h0+rI0SFI=,iv:CzIX0REU8oLn2zDgwVzsLJ9wfWl+rvKqnaKCVp3N5sA=,tag:Kv3RukYoObRqmuX6juO4nw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
